from flask import Flask, render_template, request, jsonify, send_file
from flask_cors import CORS
from routes import register_blueprints

from PIL import Image
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.lib import colors
from reportlab.lib.units import inch
from io import BytesIO
import requests
import os
import time

# ==========================
# APP INIT
# ==========================

app = Flask(__name__)
CORS(app)

# Register all blueprints
register_blueprints(app)

# ==========================
# BLOCKCHAIN (OPTIONAL)
# ==========================

BLOCKCHAIN_AVAILABLE = False
try:
    from web3 import Web3
    from blockchain_interaction import get_user_designs as _get_user_designs

    w3 = Web3(Web3.HTTPProvider("http://127.0.0.1:8545"))

    if w3.is_connected():
        BLOCKCHAIN_AVAILABLE = True

except Exception:
    pass

# ==========================
# PAGES (FRONTEND ROUTES)
# ==========================

@app.route("/")
def home():
    return render_template("index.html")


@app.route("/text_to_image")
def text_to_image():
    return render_template("text_to_image.html")


@app.route("/image_to_image")
def image_to_image():
    return render_template("image_to_image.html")


@app.route("/sketch_to_image")
def sketch_to_image():
    return render_template("sketch_to_image.html")


@app.route("/view_designs")
def view_designs():
    return render_template("view_designs.html")

# ==========================
# TEXT → IMAGE API (BLUEPRINT HANDLES GENERATION)
# ==========================

@app.route("/generate_text_to_image", methods=["POST"])
def handle_text_to_image():
    data = request.get_json()

    if not data:
        return jsonify({"error": "Invalid request"}), 400

    prompt = data.get("prompt", "").strip()

    if not prompt:
        return jsonify({"error": "No prompt provided"}), 400

    try:
        from routes.image_generation import generate_image_from_prompt

        start_time = time.time()
        image_path, image_url = generate_image_from_prompt(prompt)
        generation_time = round(time.time() - start_time, 2)

        return jsonify({
            "image_url": image_url,
            "image_path": image_path,
            "generation_time_seconds": generation_time
        })

    except Exception as e:
        return jsonify({"error": f"Generation error: {str(e)}"}), 500


# ==========================
# PDF GENERATION (NO IPFS)
# ==========================

@app.route("/generate_pdf", methods=["POST"])
def generate_pdf():
    try:
        data = request.get_json()

        image_url = data.get("image_url")
        wallet = data.get("wallet", "N/A")

        if not image_url:
            return jsonify({"error": "image_url is required"}), 400

        image = None

        try:
            response = requests.get(image_url, timeout=10)
            if response.status_code == 200:
                image = Image.open(BytesIO(response.content))
        except Exception:
            image = None

        pdf_buffer = BytesIO()
        c = canvas.Canvas(pdf_buffer, pagesize=letter)
        width, height = letter

        # Background
        c.setFillColor(colors.whitesmoke)
        c.rect(0, 0, width, height, fill=True, stroke=0)

        # Header
        c.setFillColor(colors.darkblue)
        c.rect(0, height - 80, width, 80, fill=True, stroke=0)

        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 22)
        c.drawCentredString(width / 2, height - 50, "StyleSensei Design Certificate")

        # Border
        c.setStrokeColor(colors.grey)
        c.setLineWidth(2)
        c.rect(40, 40, width - 80, height - 120)

        # Wallet
        c.setFont("Helvetica", 12)
        c.setFillColor(colors.black)
        c.drawString(60, height - 120, f"Wallet Address: {wallet}")

        # Image
        if image:
            c.drawImage(
                ImageReader(image),
                60,
                height - 450,
                width=5.5 * inch,
                height=3.5 * inch,
                mask='auto'
            )

        # Footer
        c.setFont("Helvetica-Oblique", 10)
        c.setFillColor(colors.grey)
        c.drawCentredString(width / 2, 30, "Generated by StyleSensei Platform")

        c.showPage()
        c.save()
        pdf_buffer.seek(0)

        return send_file(
            pdf_buffer,
            as_attachment=True,
            download_name="style_sensei_design_certificate.pdf",
            mimetype="application/pdf"
        )

    except Exception as e:
        return jsonify({"error": str(e)}), 500


# ==========================
# BLOCKCHAIN - GET DESIGNS
# ==========================

@app.route("/get_user_designs", methods=["GET"])
def get_user_designs_route():
    if not BLOCKCHAIN_AVAILABLE:
        return jsonify({"error": "Blockchain is only available locally"}), 503

    wallet = request.args.get("wallet")

    if not wallet:
        return jsonify({"error": "Wallet required"}), 400

    try:
        from web3 import Web3

        wallet_address = Web3.to_checksum_address(wallet)
        designs = _get_user_designs(wallet_address)

        result = [
            {"cid": d[0], "timestamp": d[1]}
            for d in designs
        ]

        return jsonify({"designs": result})

    except Exception as e:
        return jsonify({"error": str(e)}), 500
@app.route("/generate_sketch_to_image", methods=["POST"])
def generate_sketch_to_image():
    try:
        uploaded_sketch = request.files.get("sketch")
        prompt = request.form.get("prompt", "").lower().strip()

        if not uploaded_sketch or not prompt:
            return jsonify({
                "error": "Sketch and prompt required"
            }), 400

        # Detect color from prompt
        colors = [
            "red",
            "blue",
            "black",
            "white",
            "green",
            "grey",
            "pink",
            "purple"
        ]

        detected_color = None

        for color in colors:
            if color in prompt:
                detected_color = color
                break

        if not detected_color:
            return jsonify({
                "error": "Please specify a supported color"
            }), 400

        # Image file path
        image_filename = f"{detected_color}.png"

        image_path = os.path.join(
            app.root_path,
            "static",
            "dresses",
            "sketches",
            image_filename
        )

        print("Image Path:", image_path)
        print("Exists:", os.path.exists(image_path))

        if not os.path.exists(image_path):
            return jsonify({
                "error": f"Image not found: {image_filename}"
            }), 404

        # Build URL
        image_url = url_for(
            "static",
            filename=f"dresses/sketches/{image_filename}",
            _external=True
        )

        print("Generated URL:", image_url)

        return jsonify({
            "success": True,
            "image_url": image_url,
            "color_detected": detected_color,
            "sketch_used": image_filename
        })

    except Exception as e:
        print("Sketch Generation Error:", str(e))
        return jsonify({
            "error": str(e)
        }), 500

# ==========================
# MAIN
# ==========================

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=False)
